import { expect, it } from 'vitest'
import { colorLighten } from './colorLighten'

it('colorLighten', () => {
  expect(colorLighten('#0', 5)).toMatchInlineSnapshot('""')
  expect(colorLighten('#00', 5)).toMatchInlineSnapshot('""')
  expect(colorLighten('#000', 5)).toMatchInlineSnapshot('"#7f7f7f"')
  expect(colorLighten('#0006', 5)).toMatchInlineSnapshot('"#7f7f7f05"')
  expect(colorLighten('#fffff', 5)).toMatchInlineSnapshot('""')
  expect(colorLighten('#25eaa8', 5)).toMatchInlineSnapshot('"#92f4d3"')
  expect(colorLighten('#25eaa80', 5)).toMatchInlineSnapshot('""')
  expect(colorLighten('#ff008b59', 5)).toMatchInlineSnapshot('"#ff7fc559"')
  expect(colorLighten('#ff008b598', 5)).toMatchInlineSnapshot('""')
  expect(colorLighten([255, 255, 255], 5)).toMatchInlineSnapshot('"#ffffff"')
  expect(colorLighten([36, 235, 168, 0], 5)).toMatchInlineSnapshot('"#91f5d300"')
  expect(colorLighten([255, 0, 139, 0.35], 5)).toMatchInlineSnapshot('"#ff7fc559"')
  expect(colorLighten([0, 255, 36, 0.5], 5)).toMatchInlineSnapshot('"#7fff917f"')
  expect(colorLighten([0, 0, 0, 0.78], 5)).toMatchInlineSnapshot('"#7f7f7fc6"')
  expect(colorLighten([217], 5)).toMatchInlineSnapshot('""')
  expect(colorLighten([217, 8], 5)).toMatchInlineSnapshot('""')
  expect(colorLighten([217, 8, 16], 5)).toMatchInlineSnapshot('"#ec8387"')
  expect(colorLighten([217, 8, 16, 1], 5)).toMatchInlineSnapshot('"#ec8387ff"')
  expect(colorLighten('#25eaa8', 0)).toMatchInlineSnapshot('"#25eaa8"')
  expect(colorLighten('#25eaa8', 1)).toMatchInlineSnapshot('"#3aecb0"')
  expect(colorLighten('#25eaa8', 2)).toMatchInlineSnapshot('"#50eeb9"')
  expect(colorLighten('#25eaa8', 3)).toMatchInlineSnapshot('"#66f0c2"')
  expect(colorLighten('#25eaa8', 4)).toMatchInlineSnapshot('"#7cf2ca"')
  expect(colorLighten('#25eaa8', 5)).toMatchInlineSnapshot('"#92f4d3"')
  expect(colorLighten('#25eaa8', 6)).toMatchInlineSnapshot('"#a7f6dc"')
  expect(colorLighten('#25eaa8', 7)).toMatchInlineSnapshot('"#bdf8e4"')
  expect(colorLighten('#25eaa8', 8)).toMatchInlineSnapshot('"#d3faed"')
  expect(colorLighten('#25eaa8', 9)).toMatchInlineSnapshot('"#e9fcf6"')
  expect(colorLighten('#25eaa8', 10)).toMatchInlineSnapshot('"#ffffff"')
  expect(colorLighten('#25eaa8', 11)).toMatchInlineSnapshot('""')
})
