name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm i -g @vtrbo/ni

      - name: Install
        run: nci

      - name: Build
        run: 'nr docs:build'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: utils.vtrbo.cn
          publish_branch: docs
          publish_dir: ./docs/.vitepress/dist/
          commit_message: Release by
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
